name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    container: s1lentq/linux86buildtools:latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
            fetch-depth: 0
            submodules: true

     - name: Build using Intel C++ Compiler
       run: |
            rm -rf build && CC=icc CXX=icpc cmake -B build && cmake --build build -j8
            retVal=0
            export LD_LIBRARY_PATH="third_party/linux32:$LD_LIBRARY_PATH"

     - name: Build using GCC Compiler 9.3
       run: |
            rm -rf build-gcc && CC=gcc CXX=g++ cmake -B build-gcc && cmake --build build-gcc -j8   

     - name: Directory
       run: |
            ls -R 

     - name: Artifact1
       uses: actions/upload-artifact@v2
       with:
         name: linux32
         path: ./build/karlib_amxx_i386.so
         
     - name: Artifact2
       uses: actions/upload-artifact@v2
       with:
        name: linux32_gcc
        path: ./build-gcc/karlib_amxx_i386.so
