name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    container: s1lentq/linux86buildtools:latest

    steps:
     - name: Setup cmake
       uses: jwlawson/actions-setup-cmake@v1.12
       with:
            cmake-version: '3.16.x'

     - name: Checkout
       uses: actions/checkout@v2
       with:
            fetch-depth: 0
            submodules: true

     - name: Build using Intel C++ Compiler
       run: |
            rm -rf build && CC=icc CXX=icpc cmake -B build && cmake --build build -j8
            retVal=0
            export LD_LIBRARY_PATH="third_party/linux32:$LD_LIBRARY_PATH"

     - name: Build using GCC Compiler 9.3
       run: |
            rm -rf build-gcc && CC=gcc CXX=g++ cmake -B build-gcc && cmake --build build-gcc -j8   

     - name: Artifact1
       uses: actions/upload-artifact@v2
       with:
         name: linux
         path: ./build/karlib_amxx_i386.so

     - name: Artifact2
       uses: actions/upload-artifact@v2
       with:
        name: linux_gcc
        path: ./build-gcc/karlib_amxx_i386.so

  windows:
    name: 'Windows'
    runs-on: windows-2022
    
    env:
     solution: 'vc_project/KaraulovLab.sln'

    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
            fetch-depth: 0
            submodules: true

     - name: Add msbuild to PATH
       uses: microsoft/setup-msbuild@v1.1
       with:
            vs-prerelease: true

     - name: Build app for release
       run: msbuild ${{ env.solution }} -t:rebuild -verbosity:diag -property:Configuration=Release

     - name: Artifact1
       uses: actions/upload-artifact@v2
       with:
         name: Windows
         path: ./vc_project/Release/karlib_amxx.dll
